### ISSUE TITLE
TypeError: Class advice impossible in Python3

### ISSUE THREAD

**Issue by metanovii** [deathowl/certbot-vault-plugin#1]
Hi!
After installation plugin:
root@certbot:/# certbot
An unexpected error occurred:
TypeError: Class advice impossible in Python3.  Use the @implementer class decorator instead.
Please see the logfile '/tmp/tmph6mw23kq' for more details.

root@certbot:/# cat /tmp/tmph6mw23kq
2018-06-29 09:48:34,062:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.25.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1297, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/usr/lib/python3/dist-packages/certbot/plugins/disco.py", line 201, in find_all
    plugin_ep = PluginEntryPoint(entry_point)
  File "/usr/lib/python3/dist-packages/certbot/plugins/disco.py", line 47, in __init__
    self.plugin_cls = entry_point.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/certbot_vault/plugin.py", line 18, in <module>
    class VaultInstaller(common.Plugin):
  File "/usr/local/lib/python3.5/dist-packages/certbot_vault/plugin.py", line 19, in VaultInstaller
    zope.interface.implements(interfaces.IInstaller)
  File "/usr/local/lib/python3.5/dist-packages/zope.interface-4.4.3-py3.5-linux-x86_64.egg/zope/interface/declarations.py", line 483, in implements
    raise TypeError(_ADVICE_ERROR % 'implementer')
TypeError: Class advice impossible in Python3.  Use the @implementer class decorator instead.
2018-06-29 09:48:34,062:ERROR:certbot.log:An unexpected error occurred:

Python 3.5.2
certbot 0.25.0
certbot-vault 0.1.7

**Comment by deathowl** [comment]
Fixed in #2
